Feat: migrate to TS
KirillBazilsky/Recipe-book-server pull request #8
Opened 2024-12-03 08:34 UTC by KirillBazilsky

2024-12-03 09:46 UTC, sefaplus requested changes

2024-12-03 09:46 UTC, sefaplus commented on package.json
> +    "@types/cookie-parser": "^1.4.3",
to devdeps

2024-12-03 09:46 UTC, sefaplus commented on package.json
> +    "mongoose": "^8.8.3",
почему mongoose и там и там?

2024-12-03 09:46 UTC, sefaplus commented on src/controllers/authController.ts
> +  try {
почему это не в try? засунь в try чтобы не сильно глаза мазолило)

2024-12-03 09:46 UTC, sefaplus commented on src/controllers/authController.ts
> +    } else {
Убрать If else конструкцию. Код который завершается можно заменить на

if(!user) {
return res....
}

.. код else

2024-12-03 09:46 UTC, sefaplus commented on src/controllers/authController.ts
> +      const matched = await verifyPassword(user, password);
почему в verifyPassword передается user? 

Название говорит что оно проверяет пароль, но в реально выглядит очень не к месту что туда user выкидывает.. 

такой код не читаем) 
Код должен себя сам документировать

2024-12-03 09:46 UTC, sefaplus commented on src/controllers/authController.ts
> +      }
если пароль не совпал - кидаем ошибку но не завершаем функцию.
Плохо
Действия внизу выполнятся но ответ не будт отправлен
добавить return res..

2024-12-03 09:46 UTC, sefaplus commented on src/controllers/authController.ts
> +      });
Тут более правильным будет что в generateToken передашь пользоветеля и внутри этой функции tokenSerivice будешь payload делать.
1. Это сделает код чуть проще для понимая
2. Поддержка будет легче, если вдруг payload расширится то надо будет обновить только  generateToken fn

2024-12-03 09:46 UTC, sefaplus commented on src/controllers/authController.ts
> +      });
и еще почему эта логика все в контроллере?
У тебя же есть authService? Делать проверку пользователя там и возвращать из сервиса токен и записывать здесь

2024-12-03 09:46 UTC, sefaplus commented on src/controllers/authController.ts
> +
Same логика по созданию пользователя и токена в сервис

2024-12-03 09:46 UTC, sefaplus commented on src/controllers/favoritesController.ts
> +    const { userId } = req.user as JwtPayload;
никаких as
Ты же расширил тип зачем его переопределеять?

2024-12-03 09:46 UTC, sefaplus commented on src/controllers/recipesController.ts
> +    const { userId, name: userName } = req.user;
почему тут пустая строка

2024-12-03 09:46 UTC, sefaplus commented on src/controllers/recipesController.ts
> +
зачем ceator выделять в перменную если ты её повторно не пересипользуешь?
Просто объявить вложенный объект на 34 строке

{
...,
creator: { name: userName, id: ... }
...
}

2024-12-03 09:46 UTC, sefaplus commented on src/controllers/recipesController.ts
> +  }
Логика выглядит как переиспользуемся
Вынести в хелпер который приниает message

2024-12-03 09:46 UTC, sefaplus commented on src/controllers/recipesController.ts
> +      res.status(500).json({ error: error.message });
Такое никогда не возвращаем. Сообщения в монге могут выдать внутреннюю структуру. Можно добавить console.log ошибки но в итоге только 49 строка должна кинуть 500 (Internal Server Error)

2024-12-03 09:46 UTC, sefaplus commented on src/controllers/recipesController.ts
> +      if (error.code === 11000) {
можно в один if обернуть когда поправишь другой коммент в этом блоке

2024-12-03 09:46 UTC, sefaplus commented on src/controllers/recipesController.ts
> +      res.status(500).json({ error: error.message });
Выполнение кода в этом блоке после res.status.json не заканчивается. Ты просто ошибку на сервере ловишь потомучто headers already sent

После вызова send, json, stream и тд отправляется ответ клиенту и соединение закрывается. Повторный вызов метода провоцирует ошибку

2024-12-03 09:46 UTC, sefaplus commented on src/controllers/recipesController.ts
> +    }
в обычные IF
и делать return

2024-12-03 09:46 UTC, sefaplus commented on src/controllers/recipesController.ts
> +    const recipe = await updateRecipeById(recipeId, updatedData);
зачем выделять updatedData в переменную если ты её не используешь больше одного раза?

2024-12-03 09:46 UTC, sefaplus commented on src/controllers/recipesController.ts
> +    }
один if && return

2024-12-03 09:46 UTC, sefaplus commented on src/controllers/recipesController.ts
> +    if (!recipe) {
мы же уже проверили существование рецепта выше
после этой операции сразу 200

2024-12-03 09:46 UTC, sefaplus commented on src/controllers/recipesController.ts
> +    ): string | undefined => (typeof value === "string" ? value : undefined);
почему helper фнкция прям тут обхявляется
Унести в отдельный файл

2024-12-03 09:46 UTC, sefaplus commented on src/controllers/recipesController.ts
> +    const filter = buildFilter({
имхо мне кажется название не совсем соотвествует тому что делает функция

build == билдер, т.е. функция должна возвращать структуру builder 

Мне кажется более правильно назвать makeFilter или типо того

2024-12-03 09:46 UTC, sefaplus commented on src/controllers/recipesController.ts
> +    res.status(200).json({ recipe });
код не заканчивает работу сам

return

2024-12-03 09:46 UTC, sefaplus commented on src/controllers/usersController.ts
> +    const { userId: authUserId } = req.user as JwtPayload;
убрать as JwtPayload

2024-12-03 09:46 UTC, sefaplus commented on src/controllers/usersController.ts
> +    res.status(500).json({ message: "Unknown error occurred" });
везде такое сделать

2024-12-03 09:46 UTC, sefaplus commented on src/controllers/usersController.ts
> +    }
почему проверки !req.user тут идут? У тебя же есть middleWare авторизации
Это делается там, ты его для этого и делал)

2024-12-03 09:46 UTC, sefaplus commented on src/controllers/usersController.ts
> +    const { userId: authUserId } = req.user as JwtPayload;
as

2024-12-03 09:46 UTC, sefaplus commented on src/controllers/usersController.ts
> +    }
убрать if else 
if(!user) {
return res
}

return res.

2024-12-03 09:46 UTC, sefaplus commented on src/middlewares/authMiddleware.ts
> +export const authMiddleware = async (req: Request, res: Response, next: NextFunction) => {
вот тут хедлится авторизация
Если польщователь не найдет или токен не пришел не вызываем next()

2024-12-03 09:46 UTC, sefaplus commented on src/server.ts
> +        app.listen(port, () => {
а зачем тут tab

2024-12-03 09:46 UTC, sefaplus commented on src/services/authServices.ts
> +  return user;
тут пароль не вовзвращается случайно?)

2024-12-03 09:46 UTC, sefaplus commented on src/services/favoritesServices.ts
>    );
в монге делать update

{ $pull: { 'recipes'': { _id: 'iddd' } } }

2024-12-03 09:46 UTC, sefaplus commented on src/services/helpers.ts
> +};
а это где то используется?

2024-12-03 09:46 UTC, sefaplus commented on src/services/helpers.ts
> +
неиспоьзуемый код удалять

2024-12-03 09:46 UTC, sefaplus commented on src/services/helpers.ts
> +};
а это где то используется?

2024-12-03 09:46 UTC, sefaplus commented on src/services/helpers.ts
> +
неиспоьзуемый код удалять

2024-12-03 09:46 UTC, sefaplus commented on src/services/recipeServices.ts
> +  }
а если нет? то просто возвращаем рецепт чет странно)

2024-12-03 09:46 UTC, sefaplus commented on src/services/recipeServices.ts
> +    const updatedRecipe: IRecipe = mergeDefined<IRecipe>(updatedData,recipe)
что за пустые строки зачем они там нужны?

2024-12-03 09:46 UTC, sefaplus commented on src/services/recipeServices.ts
> +  const filter: { [key: string]: any } = {};
используй Record<string, any>

2024-12-03 09:46 UTC, sefaplus commented on src/services/userServices.ts
> +  const updatedData: {name?: string, email?: string, password?: string} = { name, email };
не форматирован

2024-12-03 09:46 UTC, sefaplus commented on src/services/userServices.ts
> +  const updatedUser = mergeDefined<IUser>(updatedData, user);
а зачем ты передаешь IUser 
Там должно само подтягивать типы

2024-12-03 10:04 UTC, KirillBazilsky commented on src/controllers/authController.ts
> +    } else {
Остатки от попыток исправить ошибки типов в роутере, кв какой то момент он принимал функцию только если в ней не было return, когда проблему решил забыл это в нормальный вид вернуть

2024-12-03 10:12 UTC, KirillBazilsky commented on src/controllers/authController.ts
> +      }
Тоже самое, поудалаял ретерны когда разбирался с ошибками в роутере, и забыл все их вернуть назад

2024-12-03 10:27 UTC, KirillBazilsky commented on src/controllers/favoritesController.ts
> +    const { userId } = req.user as JwtPayload;
Да, это я тоже как затычку использовал, не убрал....

2024-12-03 11:02 UTC, KirillBazilsky commented on src/controllers/recipesController.ts
> +      res.status(500).json({ error: error.message });
да, там должен был быть ретерн по плану

2024-12-03 11:46 UTC, KirillBazilsky commented on src/services/authServices.ts
> +  return user;
Нет, потом в контроллере только id, name и email

2024-12-03 12:02 UTC, KirillBazilsky commented on src/services/helpers.ts
> +};
при редактировани рецепта или пользователя

2024-12-03 12:03 UTC, KirillBazilsky commented on src/services/helpers.ts
> +};
при редактировании рецепта или пользователя, проверяет какие поля переданы чтобы потом обновлять только их

2024-12-03 14:20 UTC, sefaplus requested changes

2024-12-03 14:20 UTC, sefaplus commented on src/config/constants.ts
> +]
Ой ой
такое не делаем
Лучше в объект с понятными именами

{ notFound: 'User not found' ... }

А то это не читаемо)

2024-12-03 14:20 UTC, sefaplus commented on src/controllers/authController.ts
> +      user: { name: user.name, email: user.email, id: user.id },
Это все еще бы вынести в service в контроллере логика только с засрос/ответ

2024-12-03 14:20 UTC, sefaplus commented on src/controllers/authController.ts
> +): Promise<Response | void> => {
что за приколы?? какой void?
во время ошибки void не доожно быть тогла клиент повиснет! 
Вернуть 500

2024-12-03 14:20 UTC, sefaplus commented on src/controllers/authController.ts
> +    const token = createToken(user);
тоже в сервис

2024-12-03 14:20 UTC, sefaplus commented on src/controllers/favoritesController.ts
> +): Promise<Response | void> => {
same

2024-12-03 14:20 UTC, sefaplus commented on src/controllers/favoritesController.ts
> +): Promise<Response | void> => {
same

2024-12-03 14:20 UTC, sefaplus commented on src/controllers/recipesController.ts
> +): Promise<Response | void> => {
same

2024-12-03 14:20 UTC, sefaplus commented on src/controllers/recipesController.ts
> +): Promise<Response | void> => {
same

2024-12-03 14:20 UTC, sefaplus commented on src/controllers/recipesController.ts
> +): Promise<Response | void> => {
same

2024-12-03 14:20 UTC, sefaplus commented on src/controllers/usersController.ts
> +): Promise<Response | void> => {
same

2024-12-03 14:20 UTC, sefaplus commented on src/controllers/usersController.ts
> +    const { userId: authUserId } = req.user ;
зачем пустая строка

2024-12-03 14:20 UTC, sefaplus commented on src/routes/router.ts
>  router.use('/recipes', recipesRouter);
зачем пустые строки

2024-12-03 14:20 UTC, sefaplus commented on src/services/userServices.ts
> +export const findUserById = async (id: string) => User.findById(id);
а зачем делать если ты просто пробрасываешь.. странно както..

2024-12-04 07:01 UTC, sefaplus requested changes

2024-12-04 07:01 UTC, sefaplus commented on src/controllers/authController.ts
> +    const {user, token } = await createUserWithToken(name, email, password)
форматируй код

2024-12-04 07:01 UTC, sefaplus commented on src/controllers/recipesController.ts
> +    return res.status(200).json(recipes.length ? { recipes } : { recipes: [] });
а?
Зачем?

это выражение бесмысленное если ты проверяешь длину массива и она ноль ты возвращаешь то же что там бы и лежало

2024-12-04 07:01 UTC, sefaplus commented on src/controllers/usersController.ts
> +      message: "User successfully found",
такое не надо писать
если у тебя 200 статус код то уже подразумевает найдено
Возвращать только user

2024-12-04 07:01 UTC, sefaplus commented on src/controllers/authController.ts
> +      message: "User created successfully",
same

2024-12-04 07:01 UTC, sefaplus commented on src/services/favoritesServices.ts
> +  };
почему функция объявляется в рантайме? вынести

2024-12-04 07:01 UTC, sefaplus commented on src/services/helpers.ts
> +  }
в 1 if зачем два?

2024-12-04 07:01 UTC, sefaplus commented on src/services/helpers.ts
> +  return
а в чем валидация?)

2024-12-04 07:01 UTC, sefaplus commented on src/services/helpers.ts
> +  return
либо переменуй на связанное

entityDefined или что то в духе)

2024-12-04 08:04 UTC, sefaplus approved these changes

2024-12-04 08:09 UTC, merged